display_name: fastai

icon: ./assets/images/icon.png

supported_mime_type: []

keywords:
  - fastai
  - Clash
  - ClashMeta
  - Proxy

generic_name: fastai

categories:
  - Network

startup_notify: true

include: []